[hello]
name = "hello world"
code = """.data:
    .text Hello, world!
.main:
    mov 0,@
    msg @
    cr
    lf
    ret"""
output = "Hello, world!\r\n"

[add]
name = "add"
code = """.data:
    .decimal 2
    .decimal 3
.main:
    mov 0,@
    mov 1,@
    add @,@
    msg @
    cr
    lf
    ret"""
output = "5\r\n"

[subtract]
name = "subtract"
code = """.data:
    .decimal 2
    .decimal 3
.main:
    mov 0,@
    mov 1,@
    sub @,@
    msg @
    cr
    lf
    ret"""
output = "-1\r\n"

[mul]
name = "multiply"
code = """.data:
    .decimal 2
    .decimal 3
.main:
    mov 0,@
    mov 1,@
    mul @,@
    msg @
    cr
    lf
    ret"""
output = "6\r\n"

[div]
name = "divide"
code = """.data:
    .decimal 2
    .decimal 3
.main:
    mov 1,@
    mov 0,@
    div @,@
    msg @
    cr
    lf
    ret"""
output = "1.5\r\n"

[radian]
name = "radian thing"
code = """.data:
    .text pi
    .text rad
    .text deg
    .text  is 
.main:
    mov 0,@
    get @
    movd @,0
    mov 0,@
    div @,180
    mul 2,@
    mov 3,@
    mov 2,@
    concat 360,@
    concat @,@
    concat @,@
    msg @
    cr
    lf
    ret"""
output = "360deg is 6.28318530718\r\n"
